language: minimal
before_install:
- openssl aes-256-cbc -K $encrypted_0b690858ba45_key -iv $encrypted_0b690858ba45_iv
  -in .deploy_key.enc -out /tmp/deploy_key -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_key
- ssh-add /tmp/deploy_key
addons:
  ssh_known_hosts:
  - cmr-dev.jembi.org
  - cmr-staging.jembi.org
deploy:
- provider: script
  script: ssh bahmni@cmr-dev.jembi.org 'cd ~/git/cameroon-bahmni-html;git reset --hard;git checkout dev;git pull;'
  on:
    branch: dev
- provider: script
  script: ssh bahmni@cmr-staging.jembi.org 'cd ~/git/cameroon-bahmni-html;git reset --hard;git checkout staging;git pull;'
  on:
    branch: staging
